// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  DESKTOP-LOVCSUB
// DateTime: 18.12.2019 22:34:07
// UserName: Анна
// Input file <SimpleYacc.y - 18.12.2019 22:30:59>

// options: no-lines gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using ProgramTree;

namespace SimpleParser
{
public enum Tokens {
    error=1,EOF=2,BEGIN=3,END=4,CYCLE=5,ASSIGN=6,
    SEMICOLON=7,COMMA=8,PLUS=9,MINUS=10,MULT=11,DIVISION=12,
    LEFT_BRACKET=13,RIGHT_BRACKET=14,WHILE=15,DO=16,WRITE=17,VAR=18,
    INUM=19,RNUM=20,ID=21};

public struct ValueType
{ 
			public double dVal; 
			public int iVal; 
			public string sVal; 
			public Node nVal;
			public ExprNode eVal;
			public StatementNode stVal;
			public BlockNode blVal;
       }
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from SimpleYacc.y - 18.12.2019 22:30:59
// Ýòè îáúÿâëåíèÿ äîáàâëÿþòñÿ â êëàññ GPPGParser, ïðåäñòàâëÿþùèé ñîáîé ïàðñåð, ãåíåðèðóåìûé ñèñòåìîé gppg
    public BlockNode root; // Êîðíåâîé óçåë ñèíòàêñè÷åñêîãî äåðåâà 
    public Parser(AbstractScanner<ValueType, LexLocation> scanner) : base(scanner) { }
  // End verbatim content from SimpleYacc.y - 18.12.2019 22:30:59

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[29];
  private static State[] states = new State[51];
  private static string[] nonTerms = new string[] {
      "expr", "ident", "T", "F", "assign", "statement", "cycle", "while", "write", 
      "var", "varlist", "stlist", "block", "progr", "$accept", };

  static Parser() {
    states[0] = new State(new int[]{3,4},new int[]{-14,1,-13,3});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{21,18,3,4,5,31,18,35,15,41,17,46},new int[]{-12,5,-6,50,-5,9,-2,10,-13,29,-7,30,-10,34,-8,40,-9,45});
    states[5] = new State(new int[]{4,6,7,7});
    states[6] = new State(-16);
    states[7] = new State(new int[]{21,18,3,4,5,31,18,35,15,41,17,46},new int[]{-6,8,-5,9,-2,10,-13,29,-7,30,-10,34,-8,40,-9,45});
    states[8] = new State(-4);
    states[9] = new State(-5);
    states[10] = new State(new int[]{6,11});
    states[11] = new State(new int[]{21,18,19,19,13,20},new int[]{-1,12,-3,28,-4,27,-2,17});
    states[12] = new State(new int[]{9,13,10,23,4,-12,7,-12});
    states[13] = new State(new int[]{21,18,19,19,13,20},new int[]{-3,14,-4,27,-2,17});
    states[14] = new State(new int[]{11,15,12,25,9,-13,10,-13,4,-13,7,-13,14,-13,21,-13,3,-13,5,-13,18,-13,15,-13,17,-13,16,-13});
    states[15] = new State(new int[]{21,18,19,19,13,20},new int[]{-4,16,-2,17});
    states[16] = new State(-18);
    states[17] = new State(-21);
    states[18] = new State(-11);
    states[19] = new State(-22);
    states[20] = new State(new int[]{21,18,19,19,13,20},new int[]{-1,21,-3,28,-4,27,-2,17});
    states[21] = new State(new int[]{14,22,9,13,10,23});
    states[22] = new State(-23);
    states[23] = new State(new int[]{21,18,19,19,13,20},new int[]{-3,24,-4,27,-2,17});
    states[24] = new State(new int[]{11,15,12,25,9,-14,10,-14,4,-14,7,-14,14,-14,21,-14,3,-14,5,-14,18,-14,15,-14,17,-14,16,-14});
    states[25] = new State(new int[]{21,18,19,19,13,20},new int[]{-4,26,-2,17});
    states[26] = new State(-19);
    states[27] = new State(-20);
    states[28] = new State(new int[]{11,15,12,25,9,-15,10,-15,4,-15,7,-15,14,-15,21,-15,3,-15,5,-15,18,-15,15,-15,17,-15,16,-15});
    states[29] = new State(-6);
    states[30] = new State(-7);
    states[31] = new State(new int[]{21,18,19,19,13,20},new int[]{-1,32,-3,28,-4,27,-2,17});
    states[32] = new State(new int[]{9,13,10,23,21,18,3,4,5,31,18,35,15,41,17,46},new int[]{-6,33,-5,9,-2,10,-13,29,-7,30,-10,34,-8,40,-9,45});
    states[33] = new State(-17);
    states[34] = new State(-8);
    states[35] = new State(new int[]{21,18},new int[]{-11,36,-2,39});
    states[36] = new State(new int[]{8,37,4,-26,7,-26});
    states[37] = new State(new int[]{21,18},new int[]{-2,38});
    states[38] = new State(-28);
    states[39] = new State(-27);
    states[40] = new State(-9);
    states[41] = new State(new int[]{21,18,19,19,13,20},new int[]{-1,42,-3,28,-4,27,-2,17});
    states[42] = new State(new int[]{16,43,9,13,10,23});
    states[43] = new State(new int[]{21,18,3,4,5,31,18,35,15,41,17,46},new int[]{-6,44,-5,9,-2,10,-13,29,-7,30,-10,34,-8,40,-9,45});
    states[44] = new State(-24);
    states[45] = new State(-10);
    states[46] = new State(new int[]{13,47});
    states[47] = new State(new int[]{21,18,19,19,13,20},new int[]{-1,48,-3,28,-4,27,-2,17});
    states[48] = new State(new int[]{14,49,9,13,10,23});
    states[49] = new State(-25);
    states[50] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-15, new int[]{-14,2});
    rules[2] = new Rule(-14, new int[]{-13});
    rules[3] = new Rule(-12, new int[]{-6});
    rules[4] = new Rule(-12, new int[]{-12,7,-6});
    rules[5] = new Rule(-6, new int[]{-5});
    rules[6] = new Rule(-6, new int[]{-13});
    rules[7] = new Rule(-6, new int[]{-7});
    rules[8] = new Rule(-6, new int[]{-10});
    rules[9] = new Rule(-6, new int[]{-8});
    rules[10] = new Rule(-6, new int[]{-9});
    rules[11] = new Rule(-2, new int[]{21});
    rules[12] = new Rule(-5, new int[]{-2,6,-1});
    rules[13] = new Rule(-1, new int[]{-1,9,-3});
    rules[14] = new Rule(-1, new int[]{-1,10,-3});
    rules[15] = new Rule(-1, new int[]{-3});
    rules[16] = new Rule(-13, new int[]{3,-12,4});
    rules[17] = new Rule(-7, new int[]{5,-1,-6});
    rules[18] = new Rule(-3, new int[]{-3,11,-4});
    rules[19] = new Rule(-3, new int[]{-3,12,-4});
    rules[20] = new Rule(-3, new int[]{-4});
    rules[21] = new Rule(-4, new int[]{-2});
    rules[22] = new Rule(-4, new int[]{19});
    rules[23] = new Rule(-4, new int[]{13,-1,14});
    rules[24] = new Rule(-8, new int[]{15,-1,16,-6});
    rules[25] = new Rule(-9, new int[]{17,13,-1,14});
    rules[26] = new Rule(-10, new int[]{18,-11});
    rules[27] = new Rule(-11, new int[]{-2});
    rules[28] = new Rule(-11, new int[]{-11,8,-2});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // progr -> block
{ root = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 3: // stlist -> statement
{ 
				CurrentSemanticValue.blVal = new BlockNode(ValueStack[ValueStack.Depth-1].stVal); 
			}
        break;
      case 4: // stlist -> stlist, SEMICOLON, statement
{ 
				ValueStack[ValueStack.Depth-3].blVal.Add(ValueStack[ValueStack.Depth-1].stVal); 
				CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-3].blVal; 
			}
        break;
      case 5: // statement -> assign
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 6: // statement -> block
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].blVal; }
        break;
      case 7: // statement -> cycle
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 8: // statement -> var
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 9: // statement -> while
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 10: // statement -> write
{ CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth-1].stVal; }
        break;
      case 11: // ident -> ID
{ CurrentSemanticValue.eVal = new IdNode(ValueStack[ValueStack.Depth-1].sVal); }
        break;
      case 12: // assign -> ident, ASSIGN, expr
{ CurrentSemanticValue.stVal = new AssignNode(ValueStack[ValueStack.Depth-3].eVal as IdNode, ValueStack[ValueStack.Depth-1].eVal); }
        break;
      case 13: // expr -> expr, PLUS, T
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'+'); }
        break;
      case 14: // expr -> expr, MINUS, T
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'-'); }
        break;
      case 15: // expr -> T
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 16: // block -> BEGIN, stlist, END
{ CurrentSemanticValue.blVal = ValueStack[ValueStack.Depth-2].blVal; }
        break;
      case 17: // cycle -> CYCLE, expr, statement
{ CurrentSemanticValue.stVal = new CycleNode(ValueStack[ValueStack.Depth-2].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 18: // T -> T, MULT, F
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'*'); }
        break;
      case 19: // T -> T, DIVISION, F
{ CurrentSemanticValue.eVal = new BinaryNode(ValueStack[ValueStack.Depth-3].eVal,ValueStack[ValueStack.Depth-1].eVal,'/'); }
        break;
      case 20: // T -> F
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal; }
        break;
      case 21: // F -> ident
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-1].eVal as IdNode; }
        break;
      case 22: // F -> INUM
{ CurrentSemanticValue.eVal = new IntNumNode(ValueStack[ValueStack.Depth-1].iVal); }
        break;
      case 23: // F -> LEFT_BRACKET, expr, RIGHT_BRACKET
{ CurrentSemanticValue.eVal = ValueStack[ValueStack.Depth-2].eVal; }
        break;
      case 24: // while -> WHILE, expr, DO, statement
{ CurrentSemanticValue.stVal = new WhileNode(ValueStack[ValueStack.Depth-3].eVal, ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 25: // write -> WRITE, LEFT_BRACKET, expr, RIGHT_BRACKET
{ CurrentSemanticValue.stVal = new WriteNode(ValueStack[ValueStack.Depth-2].eVal); }
        break;
      case 26: // var -> VAR, varlist
{ CurrentSemanticValue.stVal = new VarDefNode(ValueStack[ValueStack.Depth-1].stVal); }
        break;
      case 27: // varlist -> ident
{
				CurrentSemanticValue.stVal = new VarDefNode(ValueStack[ValueStack.Depth-1].eVal as IdNode); 
			}
        break;
      case 28: // varlist -> varlist, COMMA, ident
{               var val = ValueStack[ValueStack.Depth - 3].stVal as VarDefNode;

                if (val != null)
                {
                    val.Add(ValueStack[ValueStack.Depth - 1].eVal as IdNode);
                    CurrentSemanticValue.stVal = ValueStack[ValueStack.Depth - 3].stVal;
                }
			}
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


}
}
